---
- name: Get data to perform basic check
  ansible.builtin.uri:
    url: "{{ prism_v2_api }}/clusters"
    method: GET
    status_code: 200
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Authorization: "{{ nutanix_api_auth }}"
    validate_certs: "{{ validate_certs }}"
    timeout: "{{ timeout }}"
  register: basic_check

- name: Set values for global summary
  ansible.builtin.set_fact:
    global_num_clusters: "{{ basic_check.metadata.total_entities | int }}"

- name: Create a global dict for the summary
  ansible.builtin.set_fact:
    global_summary_dict: "{{ global_summary_dict | default({}) | combine({ 'global_num_clusters' : (global_summary_dict['global_num_clusters'] + global_num_clusters) }, 
     recursive=true)}}"
