---
- name: Get require details for Robo check
  block:
    - name: Set require values
      ansible.builtin.set_fact:
        uuid: "{{ item.entity_results[0].entity_id }}"
      with_items: "{{ storage_summary.json.group_results }}"
      no_log: true

    - name: Set fault Tolerant capacity values
      ansible.builtin.set_fact:
        fault_tolerant_storage: "{{storage_summary.json.group_results[0].entity_results[0].data[0]['values'][0]['values'][0] | float }}"

    - name: Set storage usage values from values_dict
      ansible.builtin.set_fact:
        current_usage: "{{values_dict[storage_summary.json.group_results[0].entity_results[0].entity_id]['storage_usage_bytes'] | float}}"

    - name: Set storage summary status
      ansible.builtin.set_fact:
        node_fault_tolerant_capacity_per: "{{ (( current_usage | float / fault_tolerant_storage | float ) * 100.00) | float | round(2) }}"
        debug_msg: "current_usage={{ current_usage }}, fault_tolerant_storage={{ fault_tolerant_storage }}"

    - name: Set values to global dict
      ansible.builtin.set_fact:
        values_dict: "{{ values_dict | combine({
          uuid : { 'node_fault_tolerant_capacity_per': (node_fault_tolerant_capacity_per | float) }},
          recursive=true)}}"
  rescue:
    - name: Set values to global dict
      ansible.builtin.set_fact:
        values_dict: "{{ values_dict | combine({
          uuid : { 'node_fault_tolerant_capacity_per': 'ERROR'}},
          recursive=true)}}"
